// <auto-generated />
using System;
using AspNetCoreTiktakProject.App.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreTiktakProject.App.DataAccess.Migrations
{
    [DbContext(typeof(TiktakContext))]
    [Migration("20231007090704_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreTiktakProject.App.DataAccess.Identities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvvNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ExpireDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnDrive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarSaleId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccuredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VirtualPosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarSaleId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarSaleId = 1,
                            CustomerId = 1,
                            DestinationPoint = "Maltepe",
                            FinishedTime = new DateTime(2023, 10, 7, 14, 7, 3, 905, DateTimeKind.Local).AddTicks(5986),
                            OccuredDate = new DateTime(2023, 10, 7, 12, 7, 3, 905, DateTimeKind.Local).AddTicks(5984),
                            Price = 275m,
                            VirtualPosId = 0
                        },
                        new
                        {
                            Id = 2,
                            CarSaleId = 2,
                            CustomerId = 2,
                            DestinationPoint = "Beşiktaş",
                            FinishedTime = new DateTime(2023, 10, 7, 13, 7, 3, 905, DateTimeKind.Local).AddTicks(5994),
                            OccuredDate = new DateTime(2023, 10, 7, 12, 7, 3, 905, DateTimeKind.Local).AddTicks(5993),
                            Price = 355m,
                            VirtualPosId = 0
                        },
                        new
                        {
                            Id = 3,
                            CarSaleId = 3,
                            CustomerId = 3,
                            DestinationPoint = "Kadıköy",
                            FinishedTime = new DateTime(2023, 10, 7, 13, 7, 3, 905, DateTimeKind.Local).AddTicks(5996),
                            OccuredDate = new DateTime(2023, 10, 7, 12, 7, 3, 905, DateTimeKind.Local).AddTicks(5995),
                            Price = 400m,
                            VirtualPosId = 0
                        });
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Location = "Beşiktaş"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Location = "Kadıköy"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Location = "Bakırköy"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Location = "Maltepe"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Location = "Maltepe"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Location = "Maltepe"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Location = "Maltepe"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Location = "Maltepe"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Location = "Maltepe"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Location = "Maltepe"
                        });
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baggage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GearType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinutePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPerson")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("CarProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 5,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 2,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 6,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 3,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 7,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 4,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 1,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 5,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 2,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 6,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 3,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 7,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 4,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 8,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 12,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 9,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 13,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 10,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 14,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 11,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 8,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 12,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 9,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 13,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 10,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 14,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 11,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 15,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 19,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 16,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 20,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 17,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 21,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 18,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 15,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 19,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 16,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 20,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 17,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 21,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 18,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 22,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 26,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 23,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 27,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 24,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            CarId = 28,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 5m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 25,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 22,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 26,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 23,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 27,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 24,
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 28,
                            Baggage = "Station",
                            Brand = "Toyota Corolla",
                            CarId = 25,
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageUrl = "/images/resim",
                            MinutePrice = 7m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        });
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("StartedPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarSales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 3,
                            CustomerId = 1,
                            StartedPoint = "Beşiktaş",
                            StartedTime = new DateTime(2023, 10, 7, 12, 7, 3, 905, DateTimeKind.Local).AddTicks(5921)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 11,
                            CustomerId = 2,
                            StartedPoint = "Bakırköy",
                            StartedTime = new DateTime(2023, 10, 7, 12, 7, 3, 905, DateTimeKind.Local).AddTicks(5938)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            CustomerId = 3,
                            StartedPoint = "Maltepe",
                            StartedTime = new DateTime(2023, 10, 7, 12, 7, 3, 905, DateTimeKind.Local).AddTicks(5940)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Bill", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", "CarSale")
                        .WithMany("Bills")
                        .HasForeignKey("CarSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarSale");
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.Entity.Entity.Car", "Car")
                        .WithOne("CarProperty")
                        .HasForeignKey("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.Entity.Entity.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Car", b =>
                {
                    b.Navigation("CarProperty")
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
