// <auto-generated />
using System;
using AspNetCoreTiktakProject.App.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreTiktakProject.App.DataAccess.Migrations
{
    [DbContext(typeof(TiktakContext))]
    partial class TiktakContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreTiktakProject.App.DataAccess.Identities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvvNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLicence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ExpireDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnDrive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarPropertyId")
                        .HasColumnType("int");

                    b.Property<int>("CarSaleId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccuredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VirtualPosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarPropertyId");

                    b.HasIndex("CarSaleId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarPropertyId = 2,
                            CarSaleId = 1,
                            CustomerId = 1,
                            DestinationPoint = "Maltepe",
                            FinishedTime = new DateTime(2023, 10, 11, 18, 23, 37, 616, DateTimeKind.Local).AddTicks(871),
                            OccuredDate = new DateTime(2023, 10, 11, 16, 23, 37, 616, DateTimeKind.Local).AddTicks(869),
                            Price = 275m,
                            VirtualPosId = 0
                        },
                        new
                        {
                            Id = 2,
                            CarPropertyId = 2,
                            CarSaleId = 2,
                            CustomerId = 2,
                            DestinationPoint = "Beşiktaş",
                            FinishedTime = new DateTime(2023, 10, 11, 17, 23, 37, 616, DateTimeKind.Local).AddTicks(877),
                            OccuredDate = new DateTime(2023, 10, 11, 16, 23, 37, 616, DateTimeKind.Local).AddTicks(876),
                            Price = 355m,
                            VirtualPosId = 0
                        },
                        new
                        {
                            Id = 3,
                            CarPropertyId = 2,
                            CarSaleId = 3,
                            CustomerId = 3,
                            DestinationPoint = "Kadıköy",
                            FinishedTime = new DateTime(2023, 10, 11, 17, 23, 37, 616, DateTimeKind.Local).AddTicks(879),
                            OccuredDate = new DateTime(2023, 10, 11, 16, 23, 37, 616, DateTimeKind.Local).AddTicks(879),
                            Price = 400m,
                            VirtualPosId = 0
                        });
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baggage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GearType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageDetailUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageDetailUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageDetailUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageDetailUrl4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinutePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPerson")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 2,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 3,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 4,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 5,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 7,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 8,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 9,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Manuel",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 10,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Manuel",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 11,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 12,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 13,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 14,
                            Baggage = "Station",
                            Brand = "Mini Cooper",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/minidetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/minidetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/minidetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/minidetay4.jpeg",
                            ImageUrl = "/Templete/car-rental-html-template/img/miniana.jpg",
                            IsActive = true,
                            Location = "Beşiktaş",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 15,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 16,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 17,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 18,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 19,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 20,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 21,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 22,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 23,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 24,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2023",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 25,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 26,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 27,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 28,
                            Baggage = "Station",
                            Brand = "Renault Clio",
                            FuelType = "Benzin",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/renodetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/renodetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/renodetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/renodetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/renoana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 10m,
                            Model = "2022",
                            Plaque = "34KYN321",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 30,
                            Baggage = "Station",
                            Brand = "Volkswagen Golf",
                            FuelType = "Elektrik",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/vwgolfdetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/vwgolfdetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/vwgolfdetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/vwgolfdetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/vwgolfana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 15m,
                            Model = "2022",
                            Plaque = "34AA300",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 31,
                            Baggage = "Station",
                            Brand = "Volkswagen Passat",
                            FuelType = "Elektrik",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/vwpassatdetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/vwpassatdetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/vwpassatdetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/vwpassatdetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/vwpassatana.jpg",
                            IsActive = true,
                            Location = "Maltepe",
                            MinutePrice = 15m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 32,
                            Baggage = "Station",
                            Brand = "Mercedes Amg",
                            FuelType = "Benzinli",
                            GearType = "Manuel",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/mercedes1detay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/mercedes1detay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/mercedes1detay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/mercedes1detay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/mercedes1ana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 25m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 33,
                            Baggage = "Station",
                            Brand = "Mercedes Amg",
                            FuelType = "Benzinli",
                            GearType = "Manuel",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/mercedes1detay1.jpeg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/mercedes1detay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/mercedes1detay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/mercedes1detay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/mercedes1ana.jpg",
                            IsActive = true,
                            Location = "Bakırköy",
                            MinutePrice = 25m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 34,
                            Baggage = "Station",
                            Brand = "Mercedes G63",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/g63siyahdetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/g63siyahdetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/g63siyahdetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/g63siyahdetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/g63siyahana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 25m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 35,
                            Baggage = "Station",
                            Brand = "Mercedes G63",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/g63siyahdetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/g63siyahdetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/g63siyahdetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/g63siyahdetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/g63siyahana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 25m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 36,
                            Baggage = "Station",
                            Brand = "Fiat Egea",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/egeadetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/egeadetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/egeadetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/egeadetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/egeaana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 13m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 37,
                            Baggage = "Station",
                            Brand = "Fiat Egea",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/egeadetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/egeadetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/egeadetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/egeadetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/egeaana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 13m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 38,
                            Baggage = "Station",
                            Brand = "Fiat Egea",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/egeadetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/egeadetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/egeadetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/egeadetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/egeaana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 13m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        },
                        new
                        {
                            Id = 39,
                            Baggage = "Station",
                            Brand = "Fiat Egea",
                            FuelType = "Dizel",
                            GearType = "Otomatik",
                            ImageDetailUrl1 = "/Templete/car-rental-html-template/img/egeadetay1.jpg",
                            ImageDetailUrl2 = "/Templete/car-rental-html-template/img/egeadetay2.jpg",
                            ImageDetailUrl3 = "/Templete/car-rental-html-template/img/egeadetay3.jpg",
                            ImageDetailUrl4 = "/Templete/car-rental-html-template/img/egeadetay4.jpg",
                            ImageUrl = "/Templete/car-rental-html-template/img/egeaana.jpg",
                            IsActive = true,
                            Location = "Kadıköy",
                            MinutePrice = 13m,
                            Model = "2023",
                            Plaque = "34BB311",
                            TotalPerson = 4
                        });
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarPropertyId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("StartedPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarPropertyId");

                    b.ToTable("CarSales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarPropertyId = 1,
                            CustomerId = 1,
                            StartedPoint = "Beşiktaş",
                            StartedTime = new DateTime(2023, 10, 11, 16, 23, 37, 616, DateTimeKind.Local).AddTicks(835)
                        },
                        new
                        {
                            Id = 2,
                            CarPropertyId = 2,
                            CustomerId = 2,
                            StartedPoint = "Bakırköy",
                            StartedTime = new DateTime(2023, 10, 11, 16, 23, 37, 616, DateTimeKind.Local).AddTicks(850)
                        },
                        new
                        {
                            Id = 3,
                            CarPropertyId = 3,
                            CustomerId = 3,
                            StartedPoint = "Maltepe",
                            StartedTime = new DateTime(2023, 10, 11, 16, 23, 37, 616, DateTimeKind.Local).AddTicks(851)
                        });
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.Bill", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", "CarProperty")
                        .WithMany("Bill")
                        .HasForeignKey("CarPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", "CarSale")
                        .WithMany("Bills")
                        .HasForeignKey("CarSaleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CarProperty");

                    b.Navigation("CarSale");
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", "CarProperty")
                        .WithMany("CarSales")
                        .HasForeignKey("CarPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarProperty");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AspNetCoreTiktakProject.App.DataAccess.Identities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarProperty", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("CarSales");
                });

            modelBuilder.Entity("AspNetCoreTiktakProject.App.Entity.Entity.CarSale", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
